require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'SubridhhiApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

  pod 'agora-react-native-rtm', :path => '../node_modules/agora-react-native-rtm'

  pod 'RNCallKeep', :path => '../node_modules/react-native-callkeep'

  target 'SubridhhiAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'SubridhhiApp-tvOS' do
  # Pods for SubridhhiApp-tvOS

  target 'SubridhhiApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
